services:
  - type: web
    name: dataheal-ai
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn dataheal_ai.wsgi:application"
    envVars:
      - key: RENDER
        value: "true"
      - key: DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.6"
