# Generated by Django 4.2.29 on 2026-03-04 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('total_records', models.IntegerField(default=0)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_number', models.IntegerField()),
                ('data', models.JSONField()),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('explanation', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('clean', 'بيانات سليمة'), ('review', 'تحتاج مراجعة'), ('error', 'خطأ منطقي'), ('pending', 'قيد المعالجة')], default='pending', max_length=20)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='validator.surveydataset')),
            ],
            options={
                'ordering': ['record_number'],
            },
        ),
    ]
